// There are generally two deployment options. If additional are required, add them here

Databricks needs access to a cross-account IAM role in your AWS account to launch clusters into the VPC of the new workspace. This Quick Start provides the following two deployment options:

IMPORTANT: Select option 1 if you have the privilege to create an IAM role in your account, otherwise select option 2. Note that option 2 requires you to configure IAM roles prior to launching the deployment.

* Deploy a Databricks workspace and create a *new* cross-account IAM role. You must have sufficient permissions to create a new IAM role.
* Deploy a Databricks workspace and use an *existing* cross-account IAM role. You can create an appropriate role and policy for your deployment type by following these https://docs.databricks.com/administration-guide/account-api/iam-role.html[steps]. For this deployment option, create an additional IAM role with the following permissions:

. Embed the *AWSLambdaBasicExecutionRole* policy.
. Configure the inline policy to access to the Quick Start S3 location:
----
       {
            "Sid": "S3SourceBucket",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::aws-quickstart/*",
                "arn:aws:s3:::aws-quickstart"
            ]
        }
----
[start=3]
. Configure the inline policy to allow for managing the S3 buckets: 
----
       {
            "Sid": "S3Buckets",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucket*",
                "s3:PutBucket*",
                "s3:CreateBucket",
                "s3:ListBucket",
                "s3:Delete*"
            ],
            "Resource": "arn:aws:s3:::<S3 prefix optional or *>"
        }
----
[start=4]
. If you the choose the optional customer-managed key feature, configure inline KMS permissions:
----
       {
            "Sid": "KMS",
            "Effect": "Allow",
            "Action": [
                "kms:Get*",
                "kms:PutKeyPolicy"
            ],
            "Resource": "*"
        }
---- 


