// There are generally two deployment options. If additional are required, add them here

To launch clusters into the VPC workspace, Databricks must have access to a cross-account IAM role in your AWS account. This Quick Start provides two deployment options:

IMPORTANT: Choose the first option if you can create an IAM role in your account, otherwise choose the second option. Note that the second option requires you to configure IAM roles before launching the deployment.

* Deploy a Databricks workspace, and create a new cross-account IAM role. You must have sufficient permissions to create a new IAM role.
* Deploy a Databricks workspace, and use an existing cross-account IAM role. For more information, see https://docs.databricks.com/administration-guide/account-api/iam-role.html#create-a-cross-account-role-and-an-access-policy[Create a cross-account role and an access policy^]. For this option, create an additional IAM role with the following permissions:
. Embed the *AWSLambdaBasicExecutionRole* policy.
. Configure the inline policy to access to the Quick Start S3 location:
+
----
       {
            "Sid": "S3SourceBucket",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::aws-quickstart/*",
                "arn:aws:s3:::aws-quickstart"
            ]
        }
----
+
. Configure the inline policy to allow for managing the S3 buckets: 
+
----
       {
            "Sid": "S3Buckets",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucket*",
                "s3:PutBucket*",
                "s3:CreateBucket",
                "s3:ListBucket",
                "s3:Delete*"
            ],
            "Resource": "arn:aws:s3:::<S3 prefix optional or *>"
        }
----
+
. If you choose the optional customer managed key feature, configure the AWS KMS permissions:
+
----
       {
            "Sid": "KMS",
            "Effect": "Allow",
            "Action": [
                "kms:Get*",
                "kms:PutKeyPolicy"
            ],
            "Resource": "*"
        }
---- 


